version: "3.9"
services:
    db:
        image: postgres:13.2
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypassword
        volumes: 
            - ./db/go_movies.sql:/docker-entrypoint-initdb.d/go_movies.sql
